version: '3'
services:
  go-hello:
    build: .
    image: codebadger/go-hello
    networks:
      - reverseproxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=go-hello"
      - "traefik.frontend.rule=Host:go-hello.${DOMAIN_NAME}"
      - "traefik.docker.network=traefik_reverseproxy"

networks:
  reverseproxy:
    external:
      name: traefik_reverseproxy
